# Generated by Django 4.2.5 on 2024-01-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_alter_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Specialization',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dentistry', 'Dentistry')], default='Cardiology', max_length=30),
        ),
    ]
