# Generated by Django 4.2.5 on 2024-01-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0007_alter_doctor_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_subject',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='text',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
