# Generated by Django 4.2.5 on 2024-01-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0010_appointment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
