# Generated by Django 4.2.5 on 2024-01-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0011_alter_doctor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_picture',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
