# Generated by Django 4.2.5 on 2024-01-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0017_remove_prescription_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='completed_appointments',
            field=models.IntegerField(default=0),
        ),
    ]
