# Generated by Django 4.2.5 on 2024-01-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0018_doctor_completed_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='completed_appointments',
            field=models.IntegerField(default=1),
        ),
    ]
